### ISSUE TITLE
[Azure] The system cannot find the file specified

### ISSUE THREAD

**Issue by Interplay** [initstring/cloud_enum#16]
When running the Azure enumerations, getting an **FileNotFoundError: [WinError 2] The system cannot find the file specified** error. However - I have verified the AWS and GCP enumerations are able to be ran just fine.

I have attempted to fix the file paths defaults within _cloud_enum.py/parse_arguements()_ to fit Windows conventions, however that did not change anything. 

```python
   # Use included mutations file by default, or let the user provide one
    parser.add_argument('-m', '--mutations', type=str, action='store',
                        default=script_path + '\\enum_tools\\fuzz.txt',
                        help='Mutations. Default: enum_tools/fuzz.txt')
```

```python
    # Use include container brute-force or let the user provide one
    parser.add_argument('-b', '--brute', type=str, action='store',
                        default=script_path + '\\enum_tools\\fuzz.txt',
                        help='List to brute-force Azure container names.'
                        '  Default: enum_tools/fuzz.txt')
```

Running on Windows 10

**Example Run:**
![cloud_enum_az](https://user-images.githubusercontent.com/15710842/67900226-09a11900-fb32-11e9-9c0d-87465f8c27fe.PNG)

**Comment by initstring** [comment]
Hi @Interplay!

Thanks so much for taking the time to open an issue.

The stack trace points to the "fast_dns_lookup" function in utils.py. This function uses the subprocess to call the `host` OS command line tool, which will fail on a Windows host.

You'll need to use a Linux-based OS to run this tool.

**Comment by Interplay** [comment]
> I added a bit to the very beginning of the README that states "must be run from a nix environment".
> 
> Hopefully that will save others time troubleshooting from within Windows.

Oof - missed that, total RTFM moment from me! Thanks for the clarification and for creating this awesome tool. Much appreciated.

**Comment by initstring** [comment]
Oh, no not your fault! After your issue was raised, I went and added that bit. It wasn't there before. Sorry, I hope my comment didn't sound rude.

A better solution would be to do some checks around this and error out more clearly on Windows, or to implement the DNS checks in python instead of using host. I may look into that in the future, but I don't ever work within Windows so just generally don't spend much time testing tools there.

Thanks again for taking the time to open the issue - it's one of the ways I can tell people are using the tool and that it's worth keeping up to date. :)

**Comment by Interplay** [comment]
No offense taken - ran on Ubuntu and the Azure functions worked perfectly!

Great tool and much kudos.
